[project]
name = "mlitchi"
version = "0.1.0"
description = ""
readme = "README.md"
authors = ["Ravindra Jaju <jaju@msync.org>"]
requires-python = ">=3.11"
dependencies = [
    "bcoding>=1.5",
    "huggingface-hub>=0.27.0",
    "jsonpickle>=4.0.1",
    "mlx-lm>=0.20.6",
    "pip>=24.3.1",
    "platformdirs>=4.3.6",
    "pylaagu",
    "spacy>=3.8.3",
    "torch>=2.5.1",
    "transformers>=4.47.1",
]

[tool.uv.sources]
pylaagu = { git = "https://github.com/jaju/pylaagu.git" }
